FROM jupyter/scipy-notebook:python-3.11

USER root

RUN apt-get update && apt-get install -y \
    gdal-bin \
    libgdal-dev \
    libspatialindex-dev \
    libgeos-dev \
    libproj-dev \
    proj-data \
    proj-bin \
    libgl1-mesa-glx \
    python3-tk \
    build-essential \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY ../requirements.txt /tmp/requirements.txt

RUN GDAL_VERSION=$(gdal-config --version) && \
    pip install --no-cache-dir GDAL==$GDAL_VERSION && \
    pip install --no-cache-dir -r /tmp/requirements.txt

USER jovyan